package com.app.entities;

import javax.persistence.*;

/*
 * 	
# table
create table teams (team_id bigint primary key auto_increment,
name varchar(100) unique ,abbreviation varchar(10) unique,owner varchar(20) not null,max_age int,
batting_avg double,wickets_taken int);
 */
@Entity
@Table(name = "teams")
public class Team {
	@Id // PK
	@GeneratedValue(strategy = GenerationType.IDENTITY) // auto incremented ids generated by hibernate
	private Long id;
	@Column(length = 100,unique = true)
	private String name;
	@Column(length = 10,unique = true)
	private String abbreviation;
	@Column(length = 20,name="owner",nullable = false)
	private String ownerName;
	@Column(name="max_age")
	private int maxAge;
	@Column(name="batting_avg")
	private double battingAvg;
	@Column(name="wickets_taken")
	private int wicketsTaken;

	public Team() {
		// TODO Auto-generated constructor stub
	}
	
	

	public Team(String name, String abbreviation, String ownerName, int maxAge, double battingAvg, int wicketsTaken) {
		super();
		this.name = name;
		this.abbreviation = abbreviation;
		this.ownerName = ownerName;
		this.maxAge = maxAge;
		this.battingAvg = battingAvg;
		this.wicketsTaken = wicketsTaken;
	}



	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAbbreviation() {
		return abbreviation;
	}

	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation;
	}

	public String getOwnerName() {
		return ownerName;
	}

	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

	public int getMaxAge() {
		return maxAge;
	}

	public void setMaxAge(int maxAge) {
		this.maxAge = maxAge;
	}

	public double getBattingAvg() {
		return battingAvg;
	}

	public void setBattingAvg(double battingAvg) {
		this.battingAvg = battingAvg;
	}

	public int getWicketsTaken() {
		return wicketsTaken;
	}

	public void setWicketsTaken(int wicketsTaken) {
		this.wicketsTaken = wicketsTaken;
	}

	@Override
	public String toString() {
		return "Team [id=" + id + ", name=" + name + ", abbreviation=" + abbreviation + ", ownerName=" + ownerName
				+ ", maxAge=" + maxAge + ", battingAvg=" + battingAvg + ", wicketsTaken=" + wicketsTaken + "]";
	}

}
