# FROM starts using the image named httpd
FROM httpd

# copy the index.html from local machine to the image
# 1st param: source path of local machine
# 2nd param: destination path (image path)
COPY ./index.html /usr/local/apache2/htdocs/